### ISSUE TITLE
License in your config file 

### ISSUE THREAD

**Issue by Thiousi** [ldanielswakman/habita-site#1]

**Comment by ldanielswakman** [comment]
Thnx good catch; updated it.

**Comment by Thiousi** [comment]
Thanks. I've published your site in https://github.com/Thiousi/kirby-repos 
In a few minutes ;)

**Comment by ldanielswakman** [comment]
Nice repo, great to have as a learning resource! I've actually set up part of the Kirby CMS (blog, members and events content types) up as an API, could be nice to mention. Been meaning to write a blog post on using Kirby as an API builder.

**Comment by Thiousi** [comment]
I'd love for you to share this! I actually run the website https://macotuts.com where we write tutorials on Kirby. It'd be a pleasure to have your contribution featured there!

I've also updated the listing of your site to include the details about the API ;)

**Comment by ldanielswakman** [comment]
That sounds nice; you mean as a sort of tutorial? Or do you have a blog of some sorts?

**Comment by Thiousi** [comment]
If you're keen to write a tutorial and agree to have it syndicated on macotuts we could do that (a-la medium with a contributor box at the bottom of the article). We also have a weekly newsletter called the Macolist where if you post this on your own blog we could feature the article. Up to you :)
We have a few people that want to contribute to macotuts and need to work on how best to welcome their content !

**Comment by ldanielswakman** [comment]
Hi @Thiousi — we talked about writing a case study/contribution on the habita.com.tr website for your Macotuts project; are you still maintaining it? Just finished writing the article for the Kirby Case Study section (should be posted soon); we could think further about an article as well?
